# src/schemas.py
"""
schemas.py — Data Validation Contracts (Pydantic Models)

Every piece of data that enters or leaves LedgerWatch AI gets checked
against these models. Think of them as "forms with strict rules."

These are NOT database tables — they are validation layers that sit
between the outside world and your database.
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

# ============================================================================
# SECTION 1: TRANSACTION SCHEMAS
# ============================================================================
# These define what a "transaction" looks like at different stages.


class TransactionBase(BaseModel):
    """
    The shared "base form" for ALL transaction representations.
    Mirrors the PaySim CSV columns exactly.

    Field(..., description="...") adds documentation that FastAPI
    auto-converts into API docs.
    """

    step: int = Field(..., description="Time step (1 step = 1 hour in PaySim)")
    type: str = Field(
        ..., description="Transaction type: PAYMENT, TRANSFER, CASH_OUT, etc."
    )
    amount: float = Field(..., gt=0, description="Transaction amount (must be > 0)")
    nameOrig: str = Field(..., description="Sender account ID")
    oldbalanceOrg: float = Field(
        ..., ge=0, description="Sender balance BEFORE transaction"
    )
    newbalanceOrig: float = Field(
        ..., ge=0, description="Sender balance AFTER transaction"
    )
    nameDest: str = Field(..., description="Recipient account ID")
    oldbalanceDest: float = Field(
        ..., ge=0, description="Recipient balance BEFORE transaction"
    )
    newbalanceDest: float = Field(
        ..., ge=0, description="Recipient balance AFTER transaction"
    )
    is_anomaly: bool = Field(
        False, description="ML prediction: True = anomaly detected"
    )
    risk_band: str = Field("Low", description="Risk level: Low, Medium, High, Critical")
    risk_score: int = Field(0, ge=0, le=100, description="Risk score 0-100")
    isFraud: Optional[int] = Field(
        None,
        ge=0,
        le=1,
        description="Ground truth: 1 = fraud, 0 = normal (used ONLY for evaluation)",
    )
    isFlaggedFraud: Optional[int] = Field(
        None, ge=0, le=1, description="PaySim's built-in rule-based fraud flag"
    )

    # What the validation rules mean:
    # gt=0  → "greater than 0" (amount can't be negative or zero)
    # ge=0  → "greater than or equal to 0" (balances can't be negative)
    # le=1  → "less than or equal to 1" (fraud labels are only 0 or 1)
    # Optional[...] = Field(None, ...) → This field CAN be missing (None is allowed)


class TransactionCreate(TransactionBase):
    """
    Used when CREATING a new transaction record.
    - From CSV ingestion (data_ingest.py)
    - From POST /predict API call

    Inherits ALL fields from TransactionBase. No extra fields needed.
    """

    pass  # "pass" means "I have nothing to add, just use everything from parent"


class TransactionRead(TransactionBase):
    """
    Used when READING a transaction FROM the database.
    Adds fields that the DATABASE creates automatically — not from the CSV.

    model_config = ConfigDict(from_attributes=True) is REQUIRED to convert
    SQLAlchemy database rows into this Pydantic model.
    """

    model_config = ConfigDict(from_attributes=True)
    # ^ This magic line tells Pydantic: "You can create this object from
    #   a SQLAlchemy ORM object." Without this, FastAPI can't send DB
    #   data as JSON in API responses.

    id: int  # Auto-generated by SQLite (row number)
    created_at: datetime  # Auto-generated timestamp when row was inserted


# ============================================================================
# SECTION 2: PREDICTION RESULT SCHEMAS
# ============================================================================
# These define what the ML model returns.


class PredictionResult(BaseModel):
    """Output of the anomaly detection pipeline."""

    model_config = ConfigDict(from_attributes=True)

    transaction_id: int
    anomaly_score: float = Field(
        ..., description="Raw Isolation Forest score (negative = more anomalous)"
    )
    risk_score: int = Field(
        ..., ge=0, le=100, description="Calibrated 0-100 risk percentile"
    )
    risk_band: Optional[str] = Field(
        None, description="Low, Medium, Elevated, High, Critical"
    )
    is_anomaly: bool = Field(..., description="True if anomaly_score indicates outlier")
    shap_values: Optional[dict] = Field(
        None, description="Feature contributions from SHAP explainability"
    )
    top_features: Optional[list[str]] = Field(
        None, description="Top 3 features driving this risk score"
    )


class BatchPredictionResponse(BaseModel):
    """
    Output of POST /batch-predict (CSV upload).
    Wraps multiple PredictionResult objects with summary stats.
    """

    total_processed: int
    anomalies_detected: int
    results: list[PredictionResult]


# ============================================================================
# SECTION 3: OCR SCHEMAS
# ============================================================================
# These define what the invoice OCR pipeline returns.


class OCRExtraction(BaseModel):
    """
    Output of the OCR pipeline for invoice parsing.
    Used by POST /ocr and the OCR Demo dashboard page.
    """

    raw_text: str = Field(
        ..., description="Full text extracted from PDF before any processing"
    )
    amount: Optional[float] = Field(None, description="Extracted monetary amount")
    date: Optional[str] = Field(None, description="Extracted date string")
    vendor: Optional[str] = Field(None, description="Extracted vendor/company name")
    confidence: float = Field(
        ..., ge=0, le=1, description="OCR engine confidence (0 = unsure, 1 = certain)"
    )
    validation_errors: list[str] = Field(
        default_factory=list, description="Missing or invalid fields found"
    )


# ============================================================================
# SECTION 4: API-ONLY SCHEMAS (added for FastAPI backend — Day 10)
# ============================================================================


class HealthResponse(BaseModel):
    """Service health check response."""

    status: str
    version: str
    model_loaded: bool
    risk_engine_loaded: bool
    ocr_available: bool
    timestamp: str


class TransactionQueryParams(BaseModel):
    """Query parameters for GET /transactions."""

    limit: int = Field(default=100, ge=1, le=1000)
    offset: int = Field(default=0, ge=0)
    risk_min: Optional[int] = Field(default=None, ge=0, le=100)
    risk_max: Optional[int] = Field(default=None, ge=0, le=100)
    transaction_type: Optional[str] = None
